SECURITY_DATA_SCHEMA = {
    "context",
    "process_name",
    "permission",
    "entity",
    "actor",
    "ip",
    "logon_id",
    "value",
    "process_id",
    "status",
}


SECURITY_EVENT_FIELD_MAPS = {
    4624: {  # An account was successfully logged on
        "LogonType": "context",
        "AuthenticationPackageName": "permission",
        "TargetUserSid": "entity",
        "SubjectUserSid": "actor",
        "ProcessName": "process_name",
        "IpAddress": "ip",
        "SubjectLogonId": "logon_id",
    },
    4634: {  # An account was logged off
        "LogonType": "context",
        "TargetUserSid": "entity",
        "TargetLogonId": "logon_id",
    },
    4648: {  # A logon was attempted using explicit credentials
        "TargetUserName": "entity",
        "SubjectUserSid": "actor",
        "TargetServerName": "context",
        "ProcessName": "process_name",
        "IpAddress": "ip",
        "SubjectLogonId": "logon_id",
    },
    4662: {  # An operation was performed on an object
        "SubjectUserSid": "actor",
        "ObjectName": "entity",
        "OperationType": "context",
        "AccessMask": "permission",
        "SubjectLogonId": "logon_id",
    },
    4672: {  # Special privileges assigned to new logon
        "SubjectUserSid": "entity",
        "PrivilegeList": "permission",
        "SubjectLogonId": "logon_id",
    },
    4697: {  # A service was installed in the system
        "SubjectUserSid": "actor",
        "SubjectLogonId": "logon_id",
        "ServiceName": "entity",
        "ServiceStartType": "context",
        "ServiceFileName": "value",
        "ClientProcessId": "process_id",
    },
    4698: {  # A scheduled task was created
        "SubjectUserSid": "actor",
        "SubjectLogonId": "logon_id",
        "TaskName": "entity",
        "TaskContent": "value",
    },
    4699: {  # A scheduled task was deleted
        "SubjectUserSid": "actor",
        "SubjectLogonId": "logon_id",
        "TaskName": "entity",
        "TaskContent": "value",
    },
    4702: {  # A scheduled task was updated
        "SubjectUserSid": "actor",
        "SubjectLogonId": "logon_id",
        "TaskName": "entity",
        "TaskContentNew": "value",
        "ClientProcessId": "process_id",
    },
    4776: {  # The computer attempted to validate credentials
        "TargetUserName": "entity",
        "Status": "status",
    },
    4798: {  # A user's local group memberships were enumerated
        "TargetSid": "entity",
        "SubjectUserSid": "actor",
        "CallerProcessId": "process_id",
    },
    4799: {  # A security-enabled local group membership was enumerated
        "SubjectUserSid": "actor",
        "SubjectLogonId": "logon_id",
        "TargetSid": "entity",
        "CallerProcessId": "process_id",
    },
    5058: {  # Key file operation
        "SubjectUserSid": "actor",
        "KeyName": "entity",
        "Operation": "context",
        "AlgorithmName": "value",
        "ClientProcessId": "process_id",
    },
    5059: {  # Cryptographic key migration
        "SubjectUserSid": "actor",
        "KeyName": "entity",
        "Operation": "context",
        "AlgorithmName": "value",
        "ClientProcessId": "process_id",
    },
    5061: {  # Cryptographic operation
        "SubjectUserSid": "actor",
        "KeyName": "entity",
        "Operation": "context",
        "AlgorithmName": "value",
    },
    5379: {  # Credential Manager credentials were read
        "ReadOperation": "context",
        "SubjectUserSid": "actor",
        "SubjectLogonId": "logon_id",
        "TargetName": "entity",
        "CountOfCredentialsReturned": "value",
        "ClientProcessId": "process_id",
    },
}
